services:
  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.development
    environment:
      - PORT
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    container_name: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    build:
        context: ./deploy/mysql
        dockerfile: Dockerfile
    env_file:
      - .env.development
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend
  swagger-ui:
#    linux/amd64
    container_name: swagger-ui
    restart: on-failure
    image: swaggerapi/swagger-ui:v5.17.13
#    platform: linux/amd64
    ports:
      - "8001:8080"
#    env_file:
#      - .env.development
    environment:
#      - SUPPORTED_SUBMIT_METHODS
      - URL=/docs/swagger.yaml
    volumes:
      - ./docs:/usr/share/nginx/html/docs

networks:
  backend:
    driver: bridge

volumes:
    db-data:

