services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./deploy/app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.development
    environment:
      - PORT
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    build:
        context: ./deploy/mysql
        dockerfile: Dockerfile
    env_file:
      - .env.development
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
#    volumes:
#  swagger-ui:
#    container_name: swagger-ui
